baseURL: 'https://new-wayland.com/blog/'
title: New Wayland
languageCode: en-gb
theme: github.com/adityatelange/hugo-PaperMod
copyright: "&copy; Neil Wilson. This blog is openly licensed via [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
    main:
        - identifier: search
          name: Search
          url: /search/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
params:
  env: production
  socialIcons: # optional
    - name: 'discord'
      link: 'https://discord.gg/JN6HKUd'
    - name: 'github'
      link: 'https://github.com/newwayland'
    - name: 'mastodon'
      link: 'https://mastodon.social/@NeilW'
    - name: 'email'
      link: 'mailto:modernmoneymatters@protonmail.com'
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  author: NeilW
  opengraph: true
  dateFormat: '_2 Jan 2006 15:04 -0700'
  intro: true
  headline: New Wayland Blog
  description: Welcome to the Future
permalinks:
  post: '/:contentbasename/'
